
language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_script:
  - echo "no tests"
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - kubectl version --short --client

Install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed 2022411/udagram-api-feed:v1
  - docker push 2022411/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user 2022411/udagram-api-user:v1
  - docker push 2022411/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend 2022411/udagram-frontend:v1
  - docker push 2022411/udagram-frontend:v1

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy 2022411/udagram-reverseproxy:v1
  - docker push 2022411/udagram-reverseproxy:v1