
language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

before_script:
  - echo "no tests"
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

Install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed 2022411/udagram-api-feed:v1
  - docker push 2022411/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user 2022411/udagram-api-user:v1
  - docker push 2022411/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend 2022411/udagram-frontend:v6
  - docker push 2022411/udagram-frontend:v6

  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy 2022411/udagram-reverseproxy:v1
  - docker push 2022411/udagram-reverseproxy:v1